// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BrandAutocompleteController from "./brand_autocomplete_controller"
application.register("brand-autocomplete", BrandAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProductNameAutocompleteController from "./product_name_autocomplete_controller"
application.register("product-name-autocomplete", ProductNameAutocompleteController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)
