include:
  - "app/**/*.rb"
  - "config/**/*.rb"
  - "lib/**/*.rb"
exclude:
  - "vendor/**/*"
  - "node_modules/**/*"
  - ".bundle/**/*"
  - "tmp/**/*"
  - "log/**/*"
  - "claude_code/**/*"
require:
  - rails
reporters:
  - rubocop
plugins:
  - solargraph-rails
max_files: 5000
